---
- hosts: localhost
  #become: true
  tasks:
    - name: install various tools
      apt:
        name:
          - colordiff
          - emacs-nox
          - git
          - htop
          - perl
          - python3
          - tree
          - vagrant
          - wget
          - xclip
        state: latest

    #- name: get dot files
      
